###########################################################################################
#####
#####   Name:  roles/nginx/tasks/main.yml
#####   
#####   Description:
#####
#####   Installs and configures nginx
#####
#####   Author
#####   Paul Silverwood (Version 1.0)
#####   
#####
###########################################################################################

- name: Install nginx package
  apt:
    name: ["nginx"]
    update_cache: yes
  become: true
  
- name: update nginx congif
  replace:  
    path: /etc/nginx/sites-available/default
    regexp: '^(\s+)(try_files \$uri \$uri\/ =404;)(\s)'
    replace: '\1\2\3\1proxy_pass  http://127\.0\.0\.1:5000/;\3'
  become: true
