###########################################################################################
#####
#####   Name: main.yml
#####   
#####   Description
#####
#####   Main Ansible Script for Deploying An EC2 Instance With A boilerplate Flask
#####
#####   Author
#####   Paul Silverwood (Version 1.0)
#####   
#####
###########################################################################################

- name: Main.yml V1.0
  hosts: remote
  gather_facts: false
  remote_user: ubuntu
  
  pre_tasks:
    - name: Install python for Ansible
      become: true
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      retries: 3
      delay: 3
      register: result
      until: result is not failed
      
  tasks:
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
    become: true
    
  - name: Remove unneeded packages from the cache
    apt:
      autoclean: yes
    become: true

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
    become: true  
    
  - name: Install other required packages and update cache
    apt:
      name: ["virtualenv", "python-pip"]
      update_cache: yes
    become: true

  - include_role:
      name: jenkins

  - include_role:
      name: flask

  - include_role:
      name: nginx


